### ISSUE TITLE
Latest version does no longer upload SSDV packets !

### ISSUE THREAD

**Issue by zanco** [rharrison/lora-gateway#2]
Hi Rob, since yesterday your updated version does no longer upload SSDV packets to ssdv.habhub.org anymore.

Tested on 2 Pi 's with different internet connection. the gateway acts like receiving but no uploads appear on habhub. Had it tested with BubUK this morning and the same happens for him.

Switching to daveake with the same gateway.cfg starts uploading the images immideately.

Sorry to be the messenger ;-)

Ben - PE2BZ

**Comment by rharrison** [comment]
I'll get on with it ASAP

Sent from my iPad

On 27 Aug 2016, at 10:08, Ben aka PE2BZ <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Rob, since yesterday your updated version does no longer upload SSDV packets to ssdv.habhub.org<http://ssdv.habhub.org> anymore.

Tested on 2 Pi 's with different internet connection. the gateway acts like receiving but no uploads appear on habhub. Had it tested with BubUK this morning and the same happens for him.

Switching to daveake with the same gateway.cfg starts uploading the images immideately.

Sorry to be the messenger ;-)

Ben - PE2BZ

-

**Comment by zanco** [comment]
Works again ! Well done
